# Introduction to python and numpy
This is a jupyter notebook. Each box on the screen is called a cell. Each cell can either contain text (such as this one) or code. Each code cell can be executed independently of other cells.
Use Shift + Enter to run a cell and move to the next one.

## Python crash course
 Taken in part from the [official python tutorials ](https://docs.python.org/3.8/tutorial/index.html)

  [Official python documentation](https://docs.python.org/3/)


In [1]:
print("Hello World!")

Hello World!


### Basic arithmetics

In [2]:
1+1 

2

In [3]:
20*2-30

10

In [4]:
8 / 5  #division always returns a floating point number

1.6

In [5]:
8//5 #floor division

1

In [6]:
17%3 #remainder of the division

2

In [7]:
2**3 #powers

8

In [8]:
# 1j is the imaginary unit
1j**2

(-1+0j)

In [9]:
(1+1j)*(1-2j) #complex multiplication

(3-1j)

### Declaring and assigning variables
Python is dynamically typed, meaning that the type (character, int, double) of a variable is inferred at runtime. Therefore you don't need to specify it when declaring variables.

In [10]:
a=2
b=5.450
c=a+b
c

7.45

### Strings

In [11]:
a="the quick brown fox jumps over the lazy dog"
print(a)

the quick brown fox jumps over the lazy dog


In [12]:
print(a[0])
print(a[-1]) # negative indices count from the end 
print(a[2:10]) # [start: stop] last index not included (i.e. 2:10 means 2,3,4,5,6,7,8,9)
print(a[2:10:2])# [start:stop:step]

t
g
e quick 
eqik


In [13]:
len(a) #length

43

### Printing

In [14]:
X=35
Y=290.39343939339

# C++ like syntax 
print("x=%d y=%.3f"%(X,Y))  

# Put variables directly in text, between curly brackets {}.
print(f"x={X} y={Y:.2e}") 

#print can also take directly objects as arguments
a=[1,2,3,4]
print(a)

x=35 y=290.393
x=35 y=2.90e+02
[1, 2, 3, 4]


### Flow control

In [15]:
#if statements
x=10
if(x>0):
    print("x is greater than zero")
elif(x==0):
    print("x is exactly zero")
else:
    print("x is negative")

x is greater than zero


In [16]:
#The range function: loop over the integers from 0 to 4
for i in range(5):
    print(i)

0
1
2
3
4


In [17]:
for i in range(5,20,2): #start,stop,step
    print(i)

5
7
9
11
13
15
17
19


In [18]:
i=0
while (i<5):
    print(i)
    i+=1

0
1
2
3
4


### Functions

In [19]:
def power(x,exp):
    return x**exp
    
power(2,3)

8

In [20]:
def volume_surface(a,b=2,c=3):#default arguments
    vol=a*b*c
    surf=a*b
    return vol,surf

volume_surface(a=2)

(12, 4)

## Numpy
Numpy is the main library for scientific computing. 
The strength of python lies in its libraries: without them it would be just another crappy programming language.
**One cannot learn python without learning the libraries**.

Python benefits from a very large community, so chances are someone else had the same problem as you and posted it on [Stack Overflow](https://stackoverflow.com/).

You can also use [ChatGPT](https://chat.openai.com/) or [Github Copilot](https://github.com/features/copilot) to help writing and debugging code. Just remember to check that the output makes sense!

Numpy complete tutorial and documentation:
1. [Official quickstart guide](https://numpy.org/doc/stable/user/quickstart.html)
 
2. [Official documentation](https://numpy.org/doc/1.21/)
 
 

To use `numpy` you need to import the module, using for example:

In [21]:
import numpy as np

### Vectors in python
There are two data structures to represent vectors
1. Python lists
2. Numpy arrays


In [22]:
a=[1,2,3,4] #syntax for python list
b=np.array([1,2,3,4]) #syntax for numpy array

In [23]:
a=[[1,2],[3,4]] #nested list
b=np.array([[1,2],[3,4]]) #nested list converted in 2 by 2 numpy array

### Arrays vs Lists
Many operations (e.g. accessing elements via index, iterating over elements, appending, removing,concatenating,...) are available both in lists and arrays.
We will describe these things only for numpy arrays, but the same applies to lists.


What are the main differences between numpy arrays and lists?
1. Type homogeneity: all elements in a numpy array share the same numeric data type, in contrast lists can contain different data types
2. Memory contiguity: a numpy array is stored in a contiguous block of memory. Lists element are not, they can be scattered around in memory.
3. Numpy arrays have fixed length along each dimension, lists do not. E.g. the list `[[1,2],[3,4,5]]` cannot be converted to numpy array, since the first and second 'rows'  of the matrix would have different lengths.

These characteristics make numpy arrays the fastest data structure for computations with vectors, matrices, tensors (intended as multi indices objects),...

**Bottom line: use numpy arrays for manipulating numerical tensors, lists for all the rest.**



In [24]:
heterogeneous_list=['qwerty',a, b, -293.929, [1,2], 1+3j, False] #there is no numpy equivalent for this
print(heterogeneous_list)
print(heterogeneous_list[4][1])

['qwerty', [[1, 2], [3, 4]], array([[1, 2],
       [3, 4]]), -293.929, [1, 2], (1+3j), False]
2


In [25]:
#both lists and numpy arrays support iteration over elements
a=[1,2,3,4]
b=np.array(a)

for x in b: #or 'for x in a:'
    print(x)

1
2
3
4


In [26]:
#The shape of an array is the length of each dimension. The size is the total number of elements. 'len' gives the length of the first dimension of the array.
b=np.ones([3,2,2])
print(b.shape) 
print(b.size)
print(len(b))

(3, 2, 2)
12
3


In [27]:
#same indexing rules as strings
squares=np.array([1,4,9,16,25,36]) #try with 'squares=[1,4,9,16,25,36]', works the same!
print(squares[2])
print(squares[2:4])
print(squares[0:4:2]) #start:stop:step
print(squares[-3])

9
[ 9 16]
[1 9]
16


In [28]:
#indexing for higher dimensional arrays
a=np.ones([4,3])
print(a)
print("element of a: ",a[1,2]) 
print("first column: ",a[:,0])
print("first row: ", a[0,:])
print("2 by 2 minor: ", a[:2,:2])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
element of a:  1.0
first column:  [1. 1. 1. 1.]
first row:  [1. 1. 1.]
2 by 2 minor:  [[1. 1.]
 [1. 1.]]


In [29]:
#Notable arrays:
print("zeros\n",np.zeros([3,3])) #3 by 3 matrix of all zeros
print("ones\n",np.ones([3,2,2])) #3 by 2 by 2 tensor of all ones
print("identity\n",np.identity(3))# 3 by 3 identity matrix
print("linspace \n",np.linspace(0,1,11))#(start,stop, number of points) 1D array of evenly spaced values 
print("arange \n",np.arange(0,1,0.1))#(start,stop, step) 1D array of evenly spaced values 
print("random in [0,1)\n",np.random.random([2, 2])) #independent random numbers uniformly distributed in the interval [0,1)

zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
identity
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
linspace 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
arange 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
random in [0,1)
 [[0.47188967 0.02686451]
 [0.75801165 0.02627253]]


#### Arrays operations
The following are common operations on arrays (not available for lists)
**Most operations act in an element-wise manner on arrays**


In [30]:
a=np.array([1,2,3,4])
b=np.array([-np.pi,2.123,1,0])
C=np.array([[1,2],[3,4]])
print(np.sum(a)) #sums all elements
print(a+b) #element-wise addition. WARNING: when applied to lists the '+' operator concatenates the lists.
print(a*b) #element-wise multiplication
print(np.exp(b)) #element-wise exponential
print(C.T) #transpose the matrix
#element-wise operations are particularly fast in arrays compared to lists.

10
[-2.14159265  4.123       4.          4.        ]
[-3.14159265  4.246       3.          0.        ]
[0.04321392 8.35616843 2.71828183 1.        ]
[[1 3]
 [2 4]]


#### Copying

In [31]:
#How NOT to copy an array (or list):
b=np.array([1,2,3,4])
b_fake_copy=b
b_fake_copy[1]=1000
print(b)# the original array was modified when modifying the 'copy'

[   1 1000    3    4]


In [32]:
#How to copy an array (or list):
b=np.array([1,2,3,4])
b_copy=np.copy(b)
b_copy[1]=1000
print(b)# the original array was NOT modified when modifying the copy

[1 2 3 4]


#### Check your shapes!
Shape of numpy arrays can be deceiving and can cause errors in computations.

In [33]:
#In this example, a is a one dimensional array, while b is a two dimensional one (i.e. it is a 1 by 4 matrix).
a=np.array([1,2,3,4])
print(a.shape)
b=np.array([[1,2,3,4]])
print(b.shape)
#The extra dimension in b can have unforeseen impacts on the operations between the arrays

(4,)
(1, 4)


In [34]:
#Reshape a so that it has the same shape as b
b2=np.reshape(a,[1,4])
print(b2.shape)

#Reshape b so that it has the same shape as a
a2=np.reshape(b,[4])
print(a2.shape)

(1, 4)
(4,)


### Exercise 1: matrix multiplication
Given two matrices $A,B$ their matrix product is the matrix  $$(AB)_{ij}=\sum_k A_{ik}B_{kj}.$$
Code the matrix product
1. Using a for loop
2. Using numpy's built in function

Then compare the time needed to run the two implementations. Which one is faster?

Hint: to measure the execution time of a cell put `%%timeit` at the beginning of the cell

In [35]:
A=np.array([[i+j for i in range(12)] for j in range(4)]) #this is a way of defining lists called 'list comprehension'
B=np.array([[1 for i in range(4)] for j in range(12)])

In [36]:
#For loop implementation:
def matmul_for_loop(A,B):
    pass #your code goes here
#numpy implementation:
#your code goes here

### Exercise 2: matrix powers
Using numpy's matrix multiplication, implement an algorithm that computes the $k$-th power of a square matrix $A$.

In [37]:
A=np.random.random([6,6])
#your code goes here

### Guided example: multiplying large sparse matrices
The fastest algorithms for multiplying two $n\times n$ matrices takes about $O(n^{2.37\dots})$ time. 

If our matrices are sparse (i.e. only a few elements are nonzero) then faster algorithms exist, but they require a different data structure for representing the matrix.
Scipy, another python library for scientific computing, uses the Compressed Sparse Row (CSR) format. 

Calling $\rho$ the fraction of nonzero elements in the matrix, the time complexity of matrix multiplication using the CSR format is $O(\rho^2 n^3)$, therefore if $\rho$ is small this algorithm is more efficient.
The following cells demonstrate the speedup. 

**Take home messages:** 
1. you should tailor your algorithms to the structure of your data. 
2. **in most situations there already exists a built in function (in numpy or scipy) that does what you want. Look for it before writing your own code.**

In [38]:
#The following code generates a matrix in which on average a fraction rho of the elements are nonzero.
def random_sparse_matrix(n,rho):
    return np.random.random([n,n])*(np.random.random([n,n])<rho)

In [43]:
#generate two random sparse matrices
n=1000
rho=0.01
A=random_sparse_matrix(n,rho)
B=random_sparse_matrix(n,rho)

In [44]:
#convert to CSR format using scipy
from scipy import sparse
A_sparse=sparse.csr_array(A)
B_sparse=sparse.csr_array(B)

In [45]:
%%timeit
A_sparse@B_sparse

229 μs ± 2.42 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
%%timeit
A@B

3.98 ms ± 141 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Ok, but how does the CSR format really work under the hood? And what about the algorithm to multiply sparse matrices?

1. **Ask ChatGPT**: the prompt "Write python code for implementing the matrix product between sparse matrices. Your algorithm should be optimized for sparse matrices" seems to work pretty well (still be critical of the output and check it).

2. Look it up on wikipedia: [Sparse Matrix](https://en.wikipedia.org/wiki/Sparse_matrix)

Why do we care about sparse matrices? The Pagerank algorithm is based on the webgraph. Is this graph sparse or dense?

#### Exercise
Change the value of `n` in the previous example and rerun the code. 

Should `n` be large or small for the CSR matrix multiplication to have an advantage? Why?

# Responsible use of LLMs (ChatGPT, Claude, Gemini, Copilot, etc.)


Given that large language models (LLMs) have become widely used in both education and research, we believe it is useful to provide examples of how to use these tools responsibly and to highlight some of the problems that can arise from an excessive use.


# Spotting Typos

One useful application of AI is spotting typos and coding errors that would otherwise take time to identify. Consider the following slow, naive function, which is intended to compute the product of four (possibly different) square matrices of the same shape:

$$(ABCD)_{ij}=\sum_{h,l,m}A_{ih}B_{hl}C_{lm}D_{mj}.$$


In [3]:
def multiply_ABCD(A,B,C,D):
    n=A.shape[0]
    R=np.zeros(n)
    for a in range(n):
        for b in range(n):
            for c in range(n):
                for d in range(n):
                    for e in range(n):
                        R[a,b]+=A[a,b]*B[c,d]*C[d,e]*D[e,b]


This function contains mistakes. Find them.


### Asking ChatGPT (5.6 Sol)

Prompt:

This function does not work, it should multiply 4 matrices in a naive way, what are the problems with it (list them)?

Output:

- np.zeros(n) creates a 1D array; use np.zeros((n, n)).
- A[a, b] has the wrong indices; use A[a, c].
- The function is missing return R.
- It assumes all matrices are square and have the same size.

Note that the last point is not really a mistake, still the LLM identified the problems very efficiently.

# Limitations of LLMs: generating overly verbose code and frequently adding unnecessary checks

We prompt chatgpt to generate a function that returns the product of 4 square matrixes in a naive way. 

In [ ]:
# LLM generated code (Chatgpt 5.6 Terra)
def multiply_ABCD(A, B, C, D):
    matrices = (A, B, C, D)

    # Check that inputs are non-empty lists of lists
    for index, M in enumerate(matrices):
        if not isinstance(M, list) or len(M) == 0:
            raise TypeError(f"Matrix {index + 1} must be a non-empty list.")

        if any(not isinstance(row, list) for row in M):
            raise TypeError(f"Matrix {index + 1} must be a list of rows.")

    n = len(A)

    # Check that every matrix is n x n
    for index, M in enumerate(matrices):
        if len(M) != n:
            raise ValueError("All matrices must have the same dimension.")

        for row in M:
            if len(row) != n:
                raise ValueError(
                    f"Matrix {index + 1} is not square with size {n} x {n}."
                )

            for value in row:
                if not isinstance(value, (int, float, complex)):
                    raise TypeError(
                        f"Matrix {index + 1} contains a non-numeric entry: {value!r}"
                    )

    R = [[0 for _ in range(n)] for _ in range(n)]

    # R = A @ B @ C @ D
    for i in range(n):
        for j in range(n):
            for k in range(n):
                for l in range(n):
                    for m in range(n):
                        R[i][j] += A[i][k] * B[k][l] * C[l][m] * D[m][j]

    return R

You can immediately see that there are a lot of unnecessary checks, making the code longer and harder to read. This is manageable in this simple example, but in more complex tasks, excessive checks can make the code harder to understand and debug. When asking an LLM to generate code, specify the assumptions it can make about the inputs and consider adding: “Keep the code concise and avoid redundant checks or checks for conditions already stated in the assumptions”.

# Sometimes, LLMs introduce approximations without explicitly mentioning them. Depending on the task, this can be a problem.

Suppose that, for an exercise of this course, you need to evaluate an integral and plot the result. An exact analytical expression may exist, but an LLM might instead generate code that uses numerical integration and plots an approximation. If you do not inspect the code, you may never notice!

Numerical integration is not (in itself) a problem, still an approximation should be tested and justified (you should also check that an approximate solution meets the exercise’s requirements).

Suppose that in an analysis course you are given the following Exercise.

>Exercise: Integrate the following function in the interval [0,1] and plot in python the function (and print the value of the integral you computed)
>    $$ f(x) = 16  \sin^2(\pi x/4)\cos^2(\pi x/4) [1 - 2\sin^2(\pi x/4)]^2 $$


The teacher of the course likely wants you to integrate this function analytically (and you can notice that $f(x)$ is just $\sin^2(x\pi)$). Still, if you give the excercise to claude you may get an answer like this:

In [ ]:

#Claude generated answer
"""
Compute the integral of
    f(x) = 16 * sin^2(pi*x/4) * cos^2(pi*x/4) * [1 - 2*sin^2(pi*x/4)]^2
over [0, 1], and plot f(x).

Note: this expression algebraically simplifies to f(x) = sin^2(pi*x),
using 16 sin^2(A)cos^2(A) = 4 sin^2(2A) and 1 - 2sin^2(A) = cos(2A),
with A = pi*x/4. This is used below only as a sanity check.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad


def f(x):
    s = np.sin(np.pi * x / 4)
    c = np.cos(np.pi * x / 4)
    return 16 * s**2 * c**2 * (1 - 2 * s**2)**2


def f_simplified(x):
    return np.sin(np.pi * x) ** 2


# --- Integrate f(x) from 0 to 1 ---
integral_value, error_estimate = quad(f, 0, 1)

print(f"Integral of f(x) from 0 to 1: {integral_value:.10f}")
print(f"Estimated numerical error:     {error_estimate:.2e}")
print(f"Exact value (1/2 - sin(2*pi)/(4*pi)): {0.5 - np.sin(2*np.pi)/(4*np.pi):.10f}")

# Sanity check against the simplified closed form sin^2(pi x)
integral_check, _ = quad(f_simplified, 0, 1)
print(f"Sanity check via sin^2(pi x):   {integral_check:.10f}")

# --- Plot f(x) ---
x_vals = np.linspace(0, 1, 500)
y_vals = f(x_vals)

plt.figure(figsize=(8, 5))
plt.plot(x_vals, y_vals, label=r"$f(x)=16\sin^2(\pi x/4)\cos^2(\pi x/4)[1-2\sin^2(\pi x/4)]^2$", color="steelblue")
plt.fill_between(x_vals, y_vals, alpha=0.2, color="steelblue", label=f"Integral ≈ {integral_value:.4f}")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.title("f(x) on [0, 1] and its integral")
plt.legend(fontsize=9)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("/mnt/user-data/outputs/function_plot.png", dpi=150)
print("Plot saved to function_plot.png")


Claude identified the simplification, but if you do not read its output carefully, you may submit a numerical approximation (with an error that depends on the integration method ) instead of the exact value 1/2.